In [5]:
import numpy as np
import pandas as pd

In [6]:
names = ['Class', 'id', 'Sequence']
data = pd.read_csv('promoters.data', names = names)

In [7]:
print(data.head())

  Class         id                                           Sequence
0     +        S10  \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataat...
1     +       AMPC  \t\ttgctatcctgacagttgtcacgctgattggtgtcgttacaat...
2     +       AROH  \t\tgtactagagaactagtgcattagcttatttttttgttatcat...
3     +      DEOP2  \taattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaa...
4     +  LEU1_TRNA  \ttcgataattaactattgacgaaaagctgaaaaccactagaatgc...

In [8]:
print(data.iloc[0])

Class                                                       +
id                                                        S10
Sequence    \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataat...
Name: 0, dtype: object

In [9]:
classes = data.loc[:, 'Class']
print(classes[:5])

0    +
1    +
2    +
3    +
4    +
Name: Class, dtype: object

### Preprocessing the dataset

In [10]:
# generate list of DNA sequences
sequences = list(data.loc[:, 'Sequence'])
dataset = {}

# loop through sequences and split into individual nucleotides

for i, seq in enumerate(sequences):
    
    # split into nucleotides, removing tab characters
    nucleotides = list(seq)
    nucleotides = [x for x in nucleotides if x != '\t']
    
    # append class assignment
    nucleotides.append(classes[i])
    
    # add to dataset
    dataset[i] = nucleotides
    
print(dataset[0])

['t', 'a', 'c', 't', 'a', 'g', 'c', 'a', 'a', 't', 'a', 'c', 'g', 'c', 't', 't', 'g', 'c', 'g', 't', 't', 'c', 'g', 'g', 't', 'g', 'g', 't', 't', 'a', 'a', 'g', 't', 'a', 't', 'g', 't', 'a', 't', 'a', 'a', 't', 'g', 'c', 'g', 'c', 'g', 'g', 'g', 'c', 't', 't', 'g', 't', 'c', 'g', 't', '+']

In [11]:
# turn dataset into pandas dataframe
df = pd.DataFrame(dataset)
print(df)

   0   1   2   3   4   5   6   7   8   9   ... 96  97  98  99  100 101 102  \
0    t   t   g   a   t   a   c   t   c   t ...   c   c   t   a   g   c   g
1    a   g   t   a   c   g   a   t   g   t ...   c   g   a   g   a   c   t
2    c   c   a   t   g   g   g   t   a   t ...   g   c   t   a   g   t   a
3    t   t   c   t   a   g   g   c   c   t ...   a   t   g   g   a   c   t
4    a   a   t   g   t   g   g   t   t   a ...   g   a   a   g   g   a   t
5    g   t   a   t   a   c   g   a   t   a ...   t   g   c   g   c   a   c
6    c   c   g   g   a   a   g   c   a   a ...   a   g   c   t   a   t   t
7    a   c   a   a   t   a   t   a   a   t ...   g   a   g   g   t   g   c
8    a   t   g   t   t   g   g   a   t   t ...   a   c   a   t   g   g   a
9    t   g   a   g   a   g   g   a   a   t ...   c   t   a   a   t   c   a
10   a   a   a   t   a   a   a   a   t   c ...   c   t   c   c   c   c   c
11   c   c   c   g   c   g   g   c   a   c ...   c   t   g   t   a   t   a
12   g   a   t   t   t   g   g   a   c   t ...   t   c   a   c   g   c   a
13   c   g   a   a   a   a   a   c   t   c ...   t   t   g   c   c   t   g
14   t   t   g   t   t   t   t   t   g   t ...   a   t   t   a   c   a   a
15   t   t   t   c   t   g   t   t   c   t ...   g   g   c   a   t   a   t
16   g   g   g   g   g   g   t   g   g   g ...   a   t   a   g   c   a   t
17   c   t   c   a   a   a   a   a   a   t ...   g   t   a   a   g   c   a
18   g   c   a   a   c   a   a   t   c   c ...   a   g   t   a   a   g   a
19   t   a   t   g   g   a   g   a   a   a ...   g   a   c   g   c   g   c
20   t   c   t   t   a   g   c   c   g   g ...   c   t   a   a   a   g   c
21   c   g   a   g   a   a   c   t   g   g ...   a   t   g   g   a   t   g
22   g   c   g   t   a   g   a   g   a   c ...   t   t   a   g   c   c   a
23   g   t   c   g   a   g   t   t   c   c ...   g   t   c   a   t   t   c
24   t   g   t   t   g   t   c   a   g   g ...   t   c   c   a   t   t   a
25   g   a   t   t   c   t   t   t   t   g ...   c   c   g   g   g   g   g
26   g   t   a   g   t   g   c   g   c   a ...   a   a   c   a   c   a   a
27   t   t   t   c   g   c   c   a   c   a ...   g   t   t   t   a   g   t
28   t   g   t   g   a   c   t   g   g   t ...   c   g   t   g   t   g   t
29   a   g   t   g   a   g   g   c   t   a ...   c   c   t   a   a   g   c
30   a   t   t   a   a   t   a   a   t   a ...   t   g   g   g   a   g   a
31   g   g   t   g   a   a   t   t   c   c ...   c   g   a   g   a   t   a
32   t   t   t   t   c   t   g   a   t   t ...   g   t   c   c   t   t   t
33   a   c   t   a   c   a   a   c   g   c ...   a   g   t   t   g   t   c
34   t   g   g   g   a   a   c   a   t   c ...   c   t   c   a   c   t   t
35   g   t   t   a   c   a   g   g   g   c ...   a   t   t   g   t   t   c
36   t   t   t   t   t   g   c   t   t   t ...   a   t   g   a   t   t   g
37   a   a   a   g   a   a   a   a   a   a ...   c   t   g   c   t   g   t
38   t   c   t   t   g   a   t   t   a   t ...   t   g   t   g   c   c   g
39   a   a   c   t   a   a   a   a   a   a ...   t   c   a   t   t   t   g
40   a   a   a   a   a   c   g   a   t   a ...   g   g   t   c   t   g   a
41   t   t   t   g   t   t   t   t   c   t ...   c   c   t   t   g   a   t
42   g   c   g   a   g   a   c   t   g   g ...   a   a   a   c   t   a   g
43   c   t   c   a   c   g   a   g   c   c ...   t   a   c   t   a   a   g
44   g   a   t   t   g   a   g   c   a   g ...   a   t   t   g   g   g   a
45   c   a   a   a   c   g   c   t   a   c ...   a   g   g   c   a   g   c
46   g   c   a   c   c   t   c   t   t   c ...   a   t   t   a   c   a   g
47   g   g   c   t   t   c   c   c   g   a ...   t   t   g   t   g   g   t
48   g   c   c   a   c   c   a   a   a   c ...   g   a   a   g   t   g   t
49   c   a   a   a   c   g   t   a   a   c ...   c   a   a   g   g   a   c
50   t   t   c   c   g   t   c   c   a   a ...   t   t   c   a   c   a   a
51   t   c   c   a   t   t   a   a   t   c ...   t   c   a   g   c   c   a
52   g   g   c   a   g   t   t   g   g   t ...   t   g   t   t   c   t   c
53   t   c   g   a   g   a   g   a   g   g ...   c   c   t   a   t   a   a
54   c   c   g   c   t   g   a   a   t   a ...   t   t   a   t   a   t   t
55   g   a   c   t   a   g   a   c   t   c ...   t   t   t   g   c   a   t
56   t   a   g   c   g   t   t   a   t   a ...   g   t   t   a   g   t   g
57   +   +   +   +   +   +   +   +   +   + ...   -   -   -   -   -   -   -

   103 104 105
0    c   c   t
1    g   t   a
2    c   c   a
3    g   g   c
4    a   t   a
5    c   c   t
6    t   c   t
7    a   t   a
8    c   c   a
9    g   a   t
10   a   a   a
11   t   t   a
12   g   g   a
13   a   g   t
14   g   c   a
15   a   c   a
16   t   t   g
17   g   c   g
18   c   t   a
19   c   a   g
20   t   a   g
21   g   a   c
22   a   c   t
23   g   g   c
24   t   g   t
25   g   g   a
26   c   t   a
27   t   c   t
28   t   t   g
29   c   t   g
30   c   g   c
31   g   a   a
32   t   g   c
33   t   g   t
34   a   g   c
35   c   g   a
36   t   t   t
37   g   t   t
38   g   t   a
39   a   t   g
40   t   t   c
41   t   t   c
42   g   g   a
43   t   c   a
44   c   t   t
45   a   g   c
46   c   a   a
47   c   a   a
48   a   a   t
49   a   g   c
50   g   g   a
51   g   a   a
52   c   g   g
53   t   g   a
54   t   a   a
55   c   a   c
56   c   c   t
57   -   -   -

[58 rows x 106 columns]

In [12]:
# transpose the df
df = df.transpose()
df.head()

  0  1  2  3  4  5  6  7  8  9  ... 48 49 50 51 52 53 54 55 56 57
0  t  a  c  t  a  g  c  a  a  t ...  g  c  t  t  g  t  c  g  t  +
1  t  g  c  t  a  t  c  c  t  g ...  c  a  t  c  g  c  c  a  a  +
2  g  t  a  c  t  a  g  a  g  a ...  c  a  c  c  c  g  g  c  g  +
3  a  a  t  t  g  t  g  a  t  g ...  a  a  c  a  a  a  c  t  c  +
4  t  c  g  a  t  a  a  t  t  a ...  c  c  g  t  g  g  t  a  g  +

[5 rows x 58 columns]

In [13]:
df.rename(columns = {57: 'Class'}, inplace = True)
print(df.shape)
df.head()

(106, 58)

   0  1  2  3  4  5  6  7  8  9  ...  48 49 50 51 52 53 54 55 56 Class
0  t  a  c  t  a  g  c  a  a  t  ...   g  c  t  t  g  t  c  g  t     +
1  t  g  c  t  a  t  c  c  t  g  ...   c  a  t  c  g  c  c  a  a     +
2  g  t  a  c  t  a  g  a  g  a  ...   c  a  c  c  c  g  g  c  g     +
3  a  a  t  t  g  t  g  a  t  g  ...   a  a  c  a  a  a  c  t  c     +
4  t  c  g  a  t  a  a  t  t  a  ...   c  c  g  t  g  g  t  a  g     +

[5 rows x 58 columns]

In [14]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,Class
count,106,106,106,106,106,106,106,106,106,106,...,106,106,106,106,106,106,106,106,106,106
unique,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,2
top,t,a,a,c,a,a,a,a,a,a,...,c,c,c,t,t,c,c,t,t,-
freq,38,34,30,30,36,42,38,34,33,36,...,36,42,31,33,35,32,29,29,34,53

In [15]:
# desribe does not tell us enough information since the attributes are text.

series = []
for name in df.columns:
    series.append(df[name].value_counts())
    
info = pd.DataFrame(series)
print(info)
details = info.transpose()
print(details)

          t     c     a     g     -     +
0      38.0  27.0  26.0  15.0   NaN   NaN
1      26.0  22.0  34.0  24.0   NaN   NaN
2      27.0  21.0  30.0  28.0   NaN   NaN
3      26.0  30.0  22.0  28.0   NaN   NaN
4      22.0  19.0  36.0  29.0   NaN   NaN
5      24.0  18.0  42.0  22.0   NaN   NaN
6      30.0  21.0  38.0  17.0   NaN   NaN
7      32.0  20.0  34.0  20.0   NaN   NaN
8      32.0  22.0  33.0  19.0   NaN   NaN
9      28.0  22.0  36.0  20.0   NaN   NaN
10     31.0  22.0  38.0  15.0   NaN   NaN
11     29.0  31.0  21.0  25.0   NaN   NaN
12     34.0  14.0  29.0  29.0   NaN   NaN
13     21.0  38.0  24.0  23.0   NaN   NaN
14     54.0  13.0  23.0  16.0   NaN   NaN
15     54.0  24.0  17.0  11.0   NaN   NaN
16     24.0  14.0  15.0  53.0   NaN   NaN
17     18.0  29.0  40.0  19.0   NaN   NaN
18     23.0  44.0  27.0  12.0   NaN   NaN
19     24.0  24.0  31.0  27.0   NaN   NaN
20     34.0  22.0  28.0  22.0   NaN   NaN
21     26.0  20.0  31.0  29.0   NaN   NaN
22     27.0  27.0  22.0  30.0   NaN   NaN
23     32.0  21.0  24.0  29.0   NaN   NaN
24     32.0  21.0  29.0  24.0   NaN   NaN
25     30.0  14.0  28.0  34.0   NaN   NaN
26     24.0  25.0  28.0  29.0   NaN   NaN
27     32.0  30.0  17.0  27.0   NaN   NaN
28     35.0  20.0  18.0  33.0   NaN   NaN
29     19.0  26.0  35.0  26.0   NaN   NaN
30     31.0  17.0  37.0  21.0   NaN   NaN
31     25.0  22.0  31.0  28.0   NaN   NaN
32     41.0  24.0  24.0  17.0   NaN   NaN
33     39.0  22.0  19.0  26.0   NaN   NaN
34     27.0  27.0  27.0  25.0   NaN   NaN
35     34.0  24.0  22.0  26.0   NaN   NaN
36     43.0  17.0  20.0  26.0   NaN   NaN
37     32.0  21.0  27.0  26.0   NaN   NaN
38     35.0  20.0  34.0  17.0   NaN   NaN
39     27.0  13.0  45.0  21.0   NaN   NaN
40     27.0  20.0  41.0  18.0   NaN   NaN
41     33.0  27.0  19.0  27.0   NaN   NaN
42     42.0  17.0  22.0  25.0   NaN   NaN
43     36.0  31.0  20.0  19.0   NaN   NaN
44     29.0  15.0  28.0  34.0   NaN   NaN
45     22.0  35.0  25.0  24.0   NaN   NaN
46     24.0  31.0  27.0  24.0   NaN   NaN
47     27.0  32.0  25.0  22.0   NaN   NaN
48     21.0  36.0  23.0  26.0   NaN   NaN
49     22.0  42.0  24.0  18.0   NaN   NaN
50     23.0  31.0  28.0  24.0   NaN   NaN
51     33.0  32.0  27.0  14.0   NaN   NaN
52     35.0  21.0  25.0  25.0   NaN   NaN
53     30.0  32.0  22.0  22.0   NaN   NaN
54     23.0  29.0  26.0  28.0   NaN   NaN
55     29.0  29.0  24.0  24.0   NaN   NaN
56     34.0  17.0  27.0  28.0   NaN   NaN
Class   NaN   NaN   NaN   NaN  53.0  53.0
      0     1     2     3     4     5     6     7     8     9  ...      48  \
t  38.0  26.0  27.0  26.0  22.0  24.0  30.0  32.0  32.0  28.0  ...    21.0
c  27.0  22.0  21.0  30.0  19.0  18.0  21.0  20.0  22.0  22.0  ...    36.0
a  26.0  34.0  30.0  22.0  36.0  42.0  38.0  34.0  33.0  36.0  ...    23.0
g  15.0  24.0  28.0  28.0  29.0  22.0  17.0  20.0  19.0  20.0  ...    26.0
-   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...     NaN
+   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...     NaN

     49    50    51    52    53    54    55    56  Class
t  22.0  23.0  33.0  35.0  30.0  23.0  29.0  34.0    NaN
c  42.0  31.0  32.0  21.0  32.0  29.0  29.0  17.0    NaN
a  24.0  28.0  27.0  25.0  22.0  26.0  24.0  27.0    NaN
g  18.0  24.0  14.0  25.0  22.0  28.0  24.0  28.0    NaN
-   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   53.0
+   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   53.0

[6 rows x 58 columns]

In [17]:
df = n_df.drop(columns = ['Class_-'])
df.rename(columns = {'Class_+': 'Class'}, inplace = True)
print(df.iloc[:5])

   0_a  0_c  0_g  0_t  1_a  1_c  1_g  1_t  2_a  2_c  ...    54_t  55_a  55_c  \
0    0    0    0    1    1    0    0    0    0    1  ...       0     0     0
1    0    0    0    1    0    0    1    0    0    1  ...       0     1     0
2    0    0    1    0    0    0    0    1    1    0  ...       0     0     1
3    1    0    0    0    1    0    0    0    0    0  ...       0     0     0
4    0    0    0    1    0    1    0    0    0    0  ...       1     1     0

   55_g  55_t  56_a  56_c  56_g  56_t  Class
0     1     0     0     0     0     1      1
1     0     0     1     0     0     0      1
2     0     0     0     0     1     0      1
3     0     1     0     1     0     0      1
4     0     0     0     0     1     0      1

[5 rows x 229 columns]

In [18]:
# Using the model_selection module to separate training and testing datasets

from sklearn import model_selection

x = np.array(df.drop(['Class'], 1))
y = np.array(df['Class'])

# split data into training and testing datasets

X_train, X_test, y_train, y_test = model_selection.train_test_split(x, y, test_size = 0.25, random_state = 47)

###  Training and Testing the classification algorithms

In [19]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score



# defining scoring method
scoring = 'accuracy'

# defining models to train

names = ["Nearest Neighbors", "Gaussian Process",
         "Decision Tree", "Random Forest", "Neural Net", 
         "Naive Bayes", "SVM Linear", "SVM RBF", "SVM Sigmoid"]

classifiers = [
    KNeighborsClassifier(n_neighbors = 3),
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth = 15),
    RandomForestClassifier(max_depth = 15, n_estimators = 15, max_features = 3),
    MLPClassifier(alpha = 1),
    GaussianNB(),
    SVC(kernel = 'linear', gamma = 'auto'),
    SVC(kernel = 'rbf',  gamma = 'auto'),
    SVC(kernel = 'sigmoid',  gamma = 'auto')
]

models = zip(names, classifiers)

# evaluate each model 
results = []
names = []

for name, model in models:
    kfold = model_selection.KFold(n_splits = 7, random_state = 47 )
    cv_rslt = model_selection.cross_val_score(model, X_train, y_train, 
                                             cv = kfold, scoring = scoring)
    results.append(cv_rslt)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_rslt.mean(), cv_rslt.std())
    print(msg)
    # test the algorithms on the validation datasets
    print("Testing:")
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    print(name)
    print(accuracy_score(y_test, predictions))
    print(classification_report(y_test, predictions))

Nearest Neighbors: 0.733766 (0.069484)
Testing:
Nearest Neighbors
0.8518518518518519
              precision    recall  f1-score   support

           0       0.89      0.73      0.80        11
           1       0.83      0.94      0.88        16

   micro avg       0.85      0.85      0.85        27
   macro avg       0.86      0.83      0.84        27
weighted avg       0.86      0.85      0.85        27

Gaussian Process: 0.796537 (0.134574)
Testing:
Gaussian Process
0.8518518518518519
              precision    recall  f1-score   support

           0       0.89      0.73      0.80        11
           1       0.83      0.94      0.88        16

   micro avg       0.85      0.85      0.85        27
   macro avg       0.86      0.83      0.84        27
weighted avg       0.86      0.85      0.85        27

Decision Tree: 0.667749 (0.139245)
Testing:
Decision Tree
0.7037037037037037
              precision    recall  f1-score   support

           0       0.62      0.73      0.67        11
           1       0.79      0.69      0.73        16

   micro avg       0.70      0.70      0.70        27
   macro avg       0.70      0.71      0.70        27
weighted avg       0.72      0.70      0.71        27

Random Forest: 0.733766 (0.049666)
Testing:
Random Forest
0.7777777777777778
              precision    recall  f1-score   support

           0       0.69      0.82      0.75        11
           1       0.86      0.75      0.80        16

   micro avg       0.78      0.78      0.78        27
   macro avg       0.77      0.78      0.78        27
weighted avg       0.79      0.78      0.78        27

C:\Users\Pratik\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Pratik\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Pratik\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Pratik\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Pratik\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Pratik\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\Users\Pratik\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

Neural Net: 0.859307 (0.081277)
Testing:
Neural Net
0.9629629629629629
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        11
           1       1.00      0.94      0.97        16

   micro avg       0.96      0.96      0.96        27
   macro avg       0.96      0.97      0.96        27
weighted avg       0.97      0.96      0.96        27

Naive Bayes: 0.746753 (0.126369)
Testing:
Naive Bayes
0.7777777777777778
              precision    recall  f1-score   support

           0       0.67      0.91      0.77        11
           1       0.92      0.69      0.79        16

   micro avg       0.78      0.78      0.78        27
   macro avg       0.79      0.80      0.78        27
weighted avg       0.81      0.78      0.78        27

SVM Linear: 0.897186 (0.102432)
Testing:
SVM Linear
0.9629629629629629
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        11
           1       1.00      0.94      0.97        16

   micro avg       0.96      0.96      0.96        27
   macro avg       0.96      0.97      0.96        27
weighted avg       0.97      0.96      0.96        27

SVM RBF: 0.795455 (0.160297)
Testing:
SVM RBF
0.8148148148148148
              precision    recall  f1-score   support

           0       0.69      1.00      0.81        11
           1       1.00      0.69      0.81        16

   micro avg       0.81      0.81      0.81        27
   macro avg       0.84      0.84      0.81        27
weighted avg       0.87      0.81      0.81        27

SVM Sigmoid: 0.591991 (0.162504)
Testing:
SVM Sigmoid
0.5925925925925926
              precision    recall  f1-score   support

           0       0.50      1.00      0.67        11
           1       1.00      0.31      0.48        16

   micro avg       0.59      0.59      0.59        27
   macro avg       0.75      0.66      0.57        27
weighted avg       0.80      0.59      0.55        27

C:\Users\Pratik\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

In [33]:
p =  SVC(kernel = 'linear', gamma = 'auto')
p.fit(X_train, y_train)
prediction = p.predict(x[98].reshape(1, -1))
print(prediction)

[0]